### PR TITLE
Installation instructions for Edge

### PR DESCRIPTION
**Pull request by revodavid**

### CODE REVIEW

**Comment by WKahnZA** [comment]
Tried installing on Edge chromium got error CRX_REQUIRED_PROOF_MISSING

**Comment by RamblingGeekUK** [comment]
It's working in the beta but not the RTM

**Comment by dpnl87** [comment]
When I try to install on Edge Beta on OSX I get the following issue:

Screenshot 2020-03-12 at 22 19 32

**Comment by clarkio** [comment]
Have you all tried with the latest release of Edge? Are things working for you better?

**Comment by revodavid** [comment]
Just tried it again and got the same error CRX_REQUIRED_PROOF_MISSING

**Comment by clarkio** [comment]
Closing this one since the instructions in #62 will work more consistently for folks.

**Comment by clarkio** [comment]
Thanks @revodavid for taking the time to write this up and test things out!

**Comment by clarkio** [comment]
Also thanks to @WKahnZA and @RamblingGeekUK for their help testing things out too 🙂👍

**Pull request closed without merging**
