### PR TITLE
Hide email in banner instead of blurring it

### PR DESCRIPTION
**Pull request by anthonychu**

### CODE REVIEW

**Comment by johnpapa** [comment]
even cooler to have an option :)

**Comment by clarkio** [comment]
@anthonychu what do you think? Should we roll with this or take the suggestions to make it an option to mask/hide?

**Comment by anthonychu** [comment]
@clarkio I think we merge or close this (since I don't think anyone would miss the blurred email). And discuss making the extension more configurable as a whole.

**Comment by clarkio** [comment]
@anthonychu Alright, I'll merge for now then.

**Pull request merged**
